In [1]:
#Done by SANJAY MALLASAMUDRAM SANTHANAM ; USC ID:3124715393
#part 1: K MEANS
import pandas as pd
import numpy as np
import math
from operator import truediv,add 
import copy

In [2]:
#read data 
data=np.loadtxt('C:/Users/Lenovo/Desktop/data.txt',delimiter=",")

In [3]:
data

array([[-1.86133124e+00, -2.99168277e+00],
       [-2.17009237e+00, -3.29231778e+00],
       [-1.01408097e+00,  3.85794990e-01],
       [-2.91294254e+00, -2.57953917e+00],
       [ 3.57207350e-02, -7.99697919e-01],
       [ 2.48350942e+00,  1.55080609e+00],
       [-5.57616974e-01,  1.84429997e+00],
       [ 1.10842255e+00,  3.08907169e+00],
       [ 3.62326849e-01, -2.01912453e+00],
       [ 2.70971410e+00,  1.71341276e+00],
       [-3.54004402e-01,  6.50573081e-01],
       [ 6.55103152e-01,  2.50487751e+00],
       [ 5.51797714e+00,  4.40317168e-01],
       [ 2.56305662e+00,  1.63039337e+00],
       [-2.08813668e+00,  2.27884440e+00],
       [ 2.50393116e+00, -8.23421912e-01],
       [-2.06663381e+00, -9.22130196e-01],
       [ 2.21526360e-02, -2.65809723e+00],
       [ 6.47043958e-01, -1.75000364e-01],
       [ 1.94538595e+00,  7.10891971e-01],
       [-8.88304367e-01, -1.48627746e+00],
       [ 1.20268655e+00,  1.44061369e-01],
       [ 3.95725154e+00, -7.12806721e-01],
       [-4.

In [4]:
#plot data for easy visualiation
import matplotlib.pyplot as plt
plt.plot(data[:,0],data[:,1],'ro')
plt.show()

<Figure size 640x480 with 1 Axes>

In [5]:
k=3
#assign center of cluster to be any of the data point
cen=copy.deepcopy([data[5],data[55],data[105]])
cen

[array([2.48350942, 1.55080609]),
 array([-3.14905203, -2.04015775]),
 array([6.03930334, 4.14499667])]

In [6]:
#randomnly assign cluster to each data point. 
cl=np.random.randint(0,high=3,size=(np.shape(data)[0]))

In [7]:
cl

array([0, 0, 0, 2, 2, 2, 2, 0, 2, 1, 0, 0, 1, 2, 1, 1, 0, 1, 0, 1, 2, 2,
       1, 0, 1, 2, 1, 0, 1, 2, 1, 0, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2,
       2, 0, 1, 0, 1, 1, 2, 2, 2, 1, 1, 2, 1, 0, 2, 1, 0, 1, 0, 0, 1, 1,
       2, 2, 2, 1, 1, 0, 0, 0, 0, 2, 1, 1, 0, 0, 1, 0, 0, 2, 0, 2, 1, 0,
       1, 0, 2, 1, 0, 0, 1, 0, 0, 2, 2, 0, 0, 0, 0, 0, 1, 1, 2, 0, 2, 1,
       0, 1, 0, 1, 0, 2, 0, 2, 1, 2, 0, 0, 0, 1, 2, 0, 2, 1, 2, 0, 1, 0,
       0, 1, 2, 2, 0, 1, 0, 0, 0, 1, 1, 2, 1, 1, 0, 0, 2, 0])

In [8]:
#cluster count i.e. count number of data points in each cluster
cluster_cnt=[-1 for _ in range(k)]


In [9]:
def euc(p1,p2):
    return math.sqrt((p1[0]-p2[0])**2+(p1[1]-p2[1])**2)

In [10]:
iter=0
while True:
    #print cluster center at each iteraation to measure progress
    print("Iter",iter)
    print("center:",cen)
    iter+=1
    #temp is variable which records previous iteretion's cluster center. 
    temp=copy.deepcopy(cl)
    #estimation step;assign data point to nearest cluster
    for i in range(0,len(data)):
        cl[i]=np.argmin(list(map(euc,[data[i],data[i],data[i]],cen)))
    #maximisation step
    #initialise cluster center and clustercount for each cluster to be zero . 
    for j in range(0,k):
        cluster_cnt[j]=0
        cen[j]=[0,0]
    #count number of data points for each cluster
    for i in range(0,len(data)):
        #increase cluster count
        cluster_cnt[cl[i]]+=1
        #add each data point to cluster center
        cen[cl[i]]=list(map(add,data[i],cen[cl[i]]))
    print(cluster_cnt)
    #divide each cluster center by number of data points in that cluster to get exact center
    for j in range(0,k):
        #if suppose a cluster isnt assigned any data point, then when we divide by zero a division error occurs.
        #This wont happen since we initially assigned cluster center to be a data point.In case we randomnly assign a point,
        #we should take care of such situations. 
        if(cluster_cnt[j]==0):
            print("Cluster ",j," has no data points")
            #alternatively assign a random center value to that cluster with no data points so that in next iteration it might
            #have a chance of getting a data point assigned.
            cen[j]=np.random.randint(low=-10,high=10,size=(2))
        #normal case
        else:
            cen[j][0]/=cluster_cnt[j]
            cen[j][1]/=cluster_cnt[j]
    #if cluster assigned doesnt change, break loop
    if(np.sum(np.subtract(temp,cl))==0):
        break

Iter 0
center: [array([2.48350942, 1.55080609]), array([-3.14905203, -2.04015775]), array([6.03930334, 4.14499667])]
[49, 64, 37]
Iter 1
center: [[1.6689846948775504, 1.0753846359387753], [-1.303590671703125, -0.992953827546875], [5.55293949081081, 4.8284624562972995]]
[32, 78, 40]
Iter 2
center: [[2.2610627391562494, 1.3543371008437501], [-1.0761545803076928, -0.8387399807179486], [5.384881445774999, 4.747021108750002]]
[29, 81, 40]
Iter 3
center: [[2.5619705510344817, 1.304000263758621], [-1.060286365320988, -0.7394930730617285], [5.384881445774999, 4.747021108750002]]
[29, 82, 39]
Iter 4
center: [[2.751347242999999, 1.2986840357931035], [-1.0553717600243908, -0.7024674495853661], [5.398990320384614, 4.813805305358977]]
[29, 83, 38]
Iter 5
center: [[2.8834971090689647, 1.358261948], [-1.0394086163975909, -0.6791968002650602], [5.433123874157894, 4.862675026605265]]
[29, 83, 38]


In [11]:
#PRINT CLUSTER CENTER
cen

[[2.8834971090689647, 1.358261948],
 [-1.0394086163975909, -0.6791968002650602],
 [5.433123874157894, 4.862675026605265]]

In [12]:
#Cluster center for K- means using library function.
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=k, random_state=0).fit(data)
print(kmeans.cluster_centers_)

[[ 3.08318256  1.77621374]
 [-0.97476572 -0.68419304]
 [ 5.62016573  5.02622634]]


In [14]:
"""
Both centers seem to match. The slight difference is because Sklearn library uses many starting points and runs the iteration many times and selects the best one. 
"""

'\nBoth centers seem to match. The slight difference is because Sklearn library uses many starting points and runs the iteration many times and selects the best one. \n'

In [67]:
#Part 2: GMM

In [68]:
data=np.loadtxt('C:/Users/Lenovo/Desktop/data.txt',delimiter=",")
data=data
N=len(data)
d=len(data[0])
print(N,d)

150 2


In [69]:
data=data.T
print(data)

[[-1.86133124e+00 -2.17009237e+00 -1.01408097e+00 -2.91294254e+00
   3.57207350e-02  2.48350942e+00 -5.57616974e-01  1.10842255e+00
   3.62326849e-01  2.70971410e+00 -3.54004402e-01  6.55103152e-01
   5.51797714e+00  2.56305662e+00 -2.08813668e+00  2.50393116e+00
  -2.06663381e+00  2.21526360e-02  6.47043958e-01  1.94538595e+00
  -8.88304367e-01  1.20268655e+00  3.95725154e+00 -4.26079398e+00
  -2.40768200e+00  2.67196907e+00 -6.57288731e-01 -8.53681790e-02
   2.06598050e+00  4.97091584e+00 -2.91112663e+00 -2.03256531e+00
  -1.73295647e-01  1.14139500e-03  2.38936033e-01 -6.98691938e-01
   2.72721289e+00 -2.03384110e+00  4.56105620e-01  2.21314257e+00
   8.38971758e-01 -1.39111649e+00  2.69569161e-01 -7.09719127e-01
  -1.34093386e+00  3.02574413e+00 -4.41998312e-01 -1.29245167e+00
  -1.69039920e+00  2.71009047e-01 -2.01348513e+00 -7.47712984e-01
  -4.76414674e-01 -2.46162963e+00  8.66405597e-01 -3.14905203e+00
  -2.63523666e+00  2.24019127e-01 -6.74825989e-01 -1.42891304e+00
  -9.88403

In [95]:
#k = no of clusters
k=3
#assign r randomnly
r=np.random.exponential(scale=10,size=(k,N))
#normalise r 
for i in range(N):
    s=np.sum(r[:,i])
    for j in range(k):
        r[j][i]=r[j][i]/s
print(r)

[[1.61281383e-02 2.56062218e-01 1.29753859e-01 1.01068812e-01
  6.21596080e-01 2.91067663e-01 3.59718030e-01 6.03393043e-01
  1.26620459e-01 5.51177636e-01 7.93323757e-01 6.42671158e-02
  5.59394426e-01 5.43912472e-01 7.28786633e-01 6.57192380e-01
  1.90383587e-01 1.18606467e-01 6.71949909e-01 2.46573481e-01
  8.77618091e-02 8.07744834e-01 2.78113002e-01 3.18433060e-01
  6.50792796e-01 1.51737598e-01 6.46463574e-01 1.85095584e-01
  3.29873503e-01 2.81599273e-01 1.34754431e-01 5.77760491e-01
  1.18948665e-01 1.04222920e-01 1.41864700e-01 4.88559168e-01
  3.75265820e-01 5.37264059e-01 4.54102541e-02 2.98690702e-01
  2.00804432e-01 1.91120083e-01 2.05106458e-01 4.72263892e-02
  3.22593807e-01 2.09191368e-01 3.16652819e-01 2.87992714e-01
  2.25011349e-01 7.22960679e-01 3.89418831e-02 3.98708818e-01
  3.06815467e-01 3.16236775e-01 7.71944206e-01 7.65681920e-02
  4.53424115e-01 8.23686545e-01 3.41921667e-01 4.96039006e-01
  4.58093389e-01 1.39235467e-01 4.52459689e-01 9.02595456e-01
  3.8390

In [96]:
#check if its normalised.
np.sum(r)

150.0

In [98]:
#assign mean u, covariance matrix E, and pi

#min max normalisation of mean
u=np.random.rand(k,d)*(np.max(data)-np.min(data))+np.min(data)

E=np.array([np.identity(d)*0.1 for _ in range(k)])
#uniformly distribute amplitude for each cluster
pi=np.array([1/k for _ in range(0,k)])
print(u,u.shape)
print(E,E.shape)
print(pi,pi.shape)

[[-3.1991359   2.46648549]
 [ 3.86991774  1.30256956]
 [ 8.57188788  0.65137803]] (3, 2)
[[[0.1 0. ]
  [0.  0.1]]

 [[0.1 0. ]
  [0.  0.1]]

 [[0.1 0. ]
  [0.  0.1]]] (3, 2, 2)
[0.33333333 0.33333333 0.33333333] (3,)


In [99]:
# probability density function(PDF)
def gau(p,x,u,E):
    #use pinv function instead of inv to calculate inverse of singular matrix
    return p/np.power((2*np.pi),d/2)*np.power(np.linalg.det(E),-0.5)*np.exp(-0.5*np.matmul(np.matmul((x-u).T,np.linalg.pinv(E)),x-u))


In [100]:
#loop counter
dum=0
while True:
    dum+=1
    #copy previous iteration's assignment value
    temp=copy.deepcopy(r)
    #Estimation step
    for i in range(0,N):
        for j in range(0,k):
            #calculate r value 
            r[j][i]=gau(pi[j],np.transpose([data[:,i]]), np.transpose([u[j]]), E[j])/ np.sum([ gau(pi[_],np.transpose([data[:,i]]), np.transpose([u[_]]), E[_]) for _ in range(0,k) ])
            
    #Maximisation step           
    for j in range(0,k):
        #Assign initlally zero vector to mean
        u[j]=np.zeros((d))
        #clculate mean
        for i in range(N):
            u[j]+=data[:,i]*r[j][i]
        u[j]/=np.sum(r[j])
        #initialise covariacne matrix to be zero vector
        E[j]=np.zeros((d,d))
        #calculate covariance matrix
        for i in range(0,N):
            E[j]+=np.matmul(np.subtract(np.transpose([data[:,i]]),np.transpose([u[j]])),np.subtract(np.transpose([data[:,i]]),np.transpose([u[j]])).T)*r[j][i]
        E[j]/=np.sum(r[j])
        #calculate amplitude
        pi[j]=np.sum(r[j])/N
    
    #print iteration info 
    print("iter:",dum)
    print("u:",u) 
    print("e:",E)
    print("pi:",pi)
    print("r:",r)
    print("sum of r:",np.sum(r))
    print(np.sum(np.abs(temp-r)))
    #if cluster assignment doesnt change below the threshold, break loop
    if(np.sum(np.abs(temp-r)))<0.01:
        break;
        
  
    

iter: 1
u: [[-1.35801671 -0.44585536]
 [ 3.1779088   2.13976863]
 [ 7.54579744  4.97713834]]
e: [[[0.7879723  0.17277644]
  [0.17277644 2.1209495 ]]

 [[4.41359835 4.28768308]
  [4.28768308 7.80447809]]

 [[0.63700544 0.19869191]
  [0.19869191 0.96943399]]]
pi: [0.44505    0.50926822 0.04568178]
r: [[1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
  4.28277619e-005 2.31613652e-068 1.00000000e+000 2.27139197e-018
  2.75920836e-021 1.74627695e-074 1.00000000e+000 2.09136896e-007
  3.90600908e-167 2.11311951e-070 1.00000000e+000 5.45136131e-081
  1.00000000e+000 4.51245193e-014 1.05085957e-020 4.36327114e-056
  1.00000000e+000 3.76559996e-036 4.76396203e-125 1.00000000e+000
  1.00000000e+000 9.83238923e-074 1.00000000e+000 2.64853900e-008
  9.28789589e-065 6.07874703e-146 1.00000000e+000 1.00000000e+000
  9.99999996e-001 1.68146784e-005 9.99867165e-001 1.00000000e+000
  1.40742857e-082 1.00000000e+000 8.32825561e-032 1.21558858e-077
  3.06720074e-032 1.00000000e+000 4.8482

In [101]:
u

array([[-0.99182225, -0.6210897 ],
       [ 3.75338436,  2.98308465],
       [ 6.49236275,  4.61175281]])

In [102]:
pi

array([0.56291151, 0.33614754, 0.10094096])

In [103]:
E

array([[[ 1.17598157, -0.06718621],
        [-0.06718621,  2.0469312 ]],

       [[ 2.50074675,  1.658824  ],
        [ 1.658824  ,  5.64825075]],

       [[ 1.44442352,  0.64507709],
        [ 0.64507709,  1.07433354]]])

In [105]:
#library function
from sklearn import mixture
g = mixture.GaussianMixture(n_components=3)
g.fit(data.T)
np.round(g.means_, 3)

array([[ 3.284,  1.929],
       [-0.962, -0.636],
       [ 5.621,  4.994]])

In [106]:
"""
From the plot it can be inferred that majority of the points are centered around the (-0.1,-0.6) point so both the methods 
give the same result. But the minor difference occurs when clustering the points in the 1st quadrant. Since they are sporadic
and scattered,the mean varies every time the algorithm is run. Hence the difference.
"""

'\nFrom the plot it can be inferred that majority of the points are centered around the (-0.1,-0.6) point so both the methods \ngive the same result. But the minor difference occurs when clustering the points in the 1st quadrant. Since they are sporadic\nand scattered,the mean varies every time the algorithm is run. Hence the difference.\n'